name: CI/CD

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  transpile:
    name: Transpile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./linky
      - run: npm run build
        working-directory: ./linky
      - run: npm ci
      - run: npm run build

  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    needs:
      - transpile
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --amd64 --aarch64 \
            --target . \
            --docker-hub ghcr.io/sileht

  publish:
    name: Build & publish Docker images
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - transpile
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: home-assistant/builder@master
        with:
          args: |
            --amd64 --aarch64 \
            --target . \
            --docker-hub ghcr.io/sileht
